//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO-LENOVOPC\\SQLEXPR2014;Initial Catalog=SFA_Softex;User ID=sa;Pas" +
            "sword=adminsa")]
        public string SFA_SoftexConnectionString {
            get {
                return ((string)(this["SFA_SoftexConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO-LENOVOPC\\SQLEXPR2014;Initial Catalog=SFA_Softex(Banceuy);User " +
            "ID=sa;Password=adminsa")]
        public string SFA_Softex_Banceuy_ConnectionString {
            get {
                return ((string)(this["SFA_Softex_Banceuy_ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO\\SQLEXPR2014;Initial Catalog=SFA_Softex(Banceuy);User ID=sa;Pas" +
            "sword=adminsa")]
        public string SFA_Softex_Banceuy_ConnectionString1 {
            get {
                return ((string)(this["SFA_Softex_Banceuy_ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO\\SQLEXPR2014;Initial Catalog=ToolSmart;User ID=sa;Password=admi" +
            "nsa")]
        public string ToolSmartConnectionString {
            get {
                return ((string)(this["ToolSmartConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO\\SQLEXPR2014;Initial Catalog=Warehouse;Integrated Security=True" +
            "")]
        public string WarehouseConnectionString {
            get {
                return ((string)(this["WarehouseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDYYO\\SQLEXPR2014;Initial Catalog=Warehouse;User ID=sa;Password=admi" +
            "nsa")]
        public string WarehouseConnectionString1 {
            get {
                return ((string)(this["WarehouseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.111;Initial Catalog=CourierDelivery;User ID=sa;Password=gaj" +
            "ah.013")]
        public string CourierDeliveryConnectionString {
            get {
                return ((string)(this["CourierDeliveryConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.111;Initial Catalog=TIKI_Courier;Persist Security Info=True" +
            ";User ID=sa;Password=gajah.013")]
        public string TIKI_CourierConnectionString {
            get {
                return ((string)(this["TIKI_CourierConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JOSHUA-PC\\SQLEXPRESS;Initial Catalog=sfa_courier;User ID=sa;Password=" +
            "cuki123")]
        public string sfa_courierConnectionString {
            get {
                return ((string)(this["sfa_courierConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NANDHA-PC;Initial Catalog=Faber_Transport;Persist Security Info=True;" +
            "User ID=sa;Password=gajah.013")]
        public string Faber_TransportConnectionString {
            get {
                return ((string)(this["Faber_TransportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=laptop-k4u6g342;Initial Catalog=TestCallPlan;User ID=sa;Password=admi" +
            "n1234567")]
        public string TestCallPlanConnectionString {
            get {
                return ((string)(this["TestCallPlanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NANDHA-PC;Initial Catalog=Faber_Transport;User ID=sa;Password=gajah.0" +
            "13")]
        public string Faber_TransportConnectionString1 {
            get {
                return ((string)(this["Faber_TransportConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-K4U6G342;Initial Catalog=Faber_Transport;User ID=sa;Password=a" +
            "dmin1234567")]
        public string Faber_TransportConnectionString2 {
            get {
                return ((string)(this["Faber_TransportConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NANDHA-PC;Initial Catalog=Avian_Transport;Persist Security Info=True;" +
            "User ID=sa;Password=gajah.013")]
        public string Avian_TransportConnectionString {
            get {
                return ((string)(this["Avian_TransportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-K4U6G342;Initial Catalog=Avian_Transport;User ID=sa;Password=a" +
            "dmin1234567")]
        public string Avian_TransportConnectionString1 {
            get {
                return ((string)(this["Avian_TransportConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JOSHUA-PC\\SQLEXPRESS;Initial Catalog=Avian_Transport;User ID=sa;Passw" +
            "ord=cuki123")]
        public string Avian_TransportConnectionString2 {
            get {
                return ((string)(this["Avian_TransportConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NANDHA-PC;Initial Catalog=Avian_Transport2;Persist Security Info=True" +
            ";User ID=sa;Password=gajah.013")]
        public string Avian_Transport2ConnectionString {
            get {
                return ((string)(this["Avian_Transport2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.159,8009;Initial Catalog=Avian_Transport;User ID=mc;Passwor" +
            "d=123")]
        public string Avian_TransportConnectionString3 {
            get {
                return ((string)(this["Avian_TransportConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.102.76.194,8009;Initial Catalog=Avian_Transport;User ID=mc;Passwo" +
            "rd=123")]
        public string Avian_TransportConnectionString4 {
            get {
                return ((string)(this["Avian_TransportConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.102.76.194,8009;Initial Catalog=INVENT;User ID=mc;Password=123")]
        public string INVENTConnectionString {
            get {
                return ((string)(this["INVENTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=117.102.76.194,8009;Initial Catalog=Avian_Transport;User ID=mc")]
        public string Avian_TransportConnectionString5 {
            get {
                return ((string)(this["Avian_TransportConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JOSHUA-PC\\SQLEXPRESS;Initial Catalog=WYETH_FIELDSERVICE;User ID=sa;Pa" +
            "ssword=cuki123")]
        public string WYETH_FIELDSERVICEConnectionString {
            get {
                return ((string)(this["WYETH_FIELDSERVICEConnectionString"]));
            }
        }
    }
}
